export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none \
  --color=bg+:#afb8cc \
  --color=bg:#dfe4ea \
  --color=border:#2887c1 \
  --color=fg:#4c545d \
  --color=gutter:#dfe4ea \
  --color=header:#ae5d00 \
  --color=hl+:#ae5d00 \
  --color=hl:#ae5d00 \
  --color=info:#8990b3 \
  --color=marker:#7e58ff \
  --color=pointer:#7e58ff \
  --color=prompt:#ae5d00 \
  --color=query:#4c545d:regular \
  --color=scrollbar:#2887c1 \
  --color=separator:#ae5d00 \
  --color=spinner:#7e58ff \
"
